version: '3.8'
services:
  coffeeshop:
    depends_on:
      - mongo
    container_name: coffeeshop
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    build:
      context: ./
    ports:
      - 5000:5000
  mongo:
    image: mongo
    restart: unless-stopped
    ports:
      - 27017:27017
    command: --quiet
