openapi: 3.0.0
info:
  title: REST API Docs
  version: 1.0.0
paths:
  /:
    get:
      description: Get all Employee by Email
      responses:
        '200':
          description: Success
components: {}
tags: []
